.TH LIBINPUT-DEBUG-EVENTS "1"
.SH NAME
libinput-debug-events \- debug helper for libinput
.SH SYNOPSIS
.B libinput-debug-events [--help]
.SH DESCRIPTION
.PP
The
.I libinput-debug-events
tool creates a libinput context and prints all events from these devices.
.PP
This is a debugging tool only, its output may change at any time. Do not
rely on the output.
.PP
This tool usually needs to be run as root to have access to the
/dev/input/eventX nodes.
.SH OPTIONS
.TP 8
.B --help
Print help
.PP
For all other options, see the output from --help. Options may be added or
removed at any time.
.SH NOTES
.PP
Events shown by this tool may not correspond to the events seen by a
different user of libinput. This tool initializes a separate context.
.PP
Events shown by this tool include key codes in plain text. Anything you type
while this tool is running will show up in the output, including your
passwords.
